- hosts: all
  tasks:
    - name: get hostname in ubuntu
      command: hostname -s
      register: hostname_output
      when: ansible_distribution == "Ubuntu" and (ansible_distribution_version | float > 23.0

    - name: show host name register
      debug:
        msg: "This is {{ hostname_output.stdout }} node"
