---
- name: test play
  hosts: all
  become: true
  vars_files:
    - myvars.yaml

  tasks:
    - name: printing package_name
      debug:
        msg: Tha package name is {{ package_name }}
    
    - name: running apt update command
      apt:
        update_cache: yes
      
    - name: install haveged package
      apt:
        name: "{{ package_name }}"
        state: present
