- hosts: all
  tasks:
    - name: task 1
      command: /bin/sleep 5
      when: ansible_hostname == 'node01'
      async: 10
      poll: 0
      register: result1
    
    - name: task 2
      command: /bin/sleep 5
      when: ansible_hostname == 'cicd'
      async: 10
      poll: 0
      register: result2
    
    - name: show result 1
      debug:
        var: result1
    
    - name: show result 2
      debug:
        var: result2
