---
- hosts: all
  vars_files:
    - secret.yaml
  vars:
    maas_username: "{{ vault_maas_username }}"
    maas_password: "{{ vault_maas_password }}"
    maas_email: "{{ vault_maas_email }}"


  tasks:
    - name: check maas installation
      shell: "which maas"
      ignore_errors: yes
      register: result 

    - name: skip on maas installed nodes
      meta: end_host
      when: result

    - name: upgrade system
      apt:
        update_cache: yes
        upgrade: yes

    - name: add maas package repository
      apt_repository:
        repo: ppa:maas/3.0

    - name: install maas package
      apt:
        update_cache: yes
        name: maas
        state: present

    - name: create maas admin user
      shell: "maas createadmin --username {{ maas_username }} --password {{ maas_password }} --email {{ maas_email }}"
