- hosts: all
  become: true
  tasks:
    - name: Configure message of the day
      copy:
        content: "Welcome to {{ item }} Linux"
        dest: /etc/motd
      notify: MOTD changed
      with_items: ["CentOS" , "Ubuntu"]
      when: ansible_distribution == item
  
  handlers:
    - name: MOTD changed  
      debug:
        msg: The MOTD was changed