- hosts: all
  tasks:
    - name: debug
      debug:
        msg: > 
          {% for entry in ansible_interfaces %}
              loop.index = {{ entry }}
          {% endfor %}
    - name: debug2
      debug:
        msg: > 
          {% for entry in range(1 , 10) %}
              {{ entry }}
          {% endfor %}
    - name: debug2
      debug:
        msg: > 
          {% for entry in range(1 , 10) %}
              {% if entry == 5 or entry == 6 %}
                {{ entry }}
              {% endif %}
          {% endfor %}
    - name: debug2
      debug:
        msg: > 
          {{ [1, 2, 3, 4, 5] | difference([2, 3, 4]) }}
